Use Macro.camelize/1
elixir-grpc/grpc-reflection pull request #36
Opened 2024-06-09 00:47 UTC by christopherlai

Fixes a bug with package names that contain underscores like `package test_service.v1.FooBar`

2024-06-09 03:45 UTC, mjheilmann requested changes
I would have preferred an issue for better conversation, but 🤷 

You have removed the test for `upcase_first/1` and the only place that it is called, but you didn't remove the now unused and untested `def upcase_first(...)`.  Please also remove the function definition when it is unused and untested.

Otherwise this looks good

2024-06-10 04:33 UTC, christopherlai commented
> I would have preferred an issue for better conversation, but 🤷
> 
> You have removed the test for `upcase_first/1` and the only place that it is called, but you didn't remove the now unused and untested `def upcase_first(...)`. Please also remove the function definition when it is unused and untested.
> 
> Otherwise this looks good

Sorry about that. Seemed like a simple issue so I opened a PR. Will remember to start a discussion in the future.

Removed `upcase_first`.

2024-06-10 22:08 UTC, mjheilmann approved these changes

2024-06-10 22:09 UTC, mjheilmann commented
> > I would have preferred an issue for better conversation, but 🤷
> > You have removed the test for `upcase_first/1` and the only place that it is called, but you didn't remove the now unused and untested `def upcase_first(...)`. Please also remove the function definition when it is unused and untested.
> > Otherwise this looks good
> 
> Sorry about that. Seemed like a simple issue so I opened a PR. Will remember to start a discussion in the future.
> 
> Removed `upcase_first`.

No worries really, I'm just a cross the Ts and dot the Is kind of guy.

2024-06-10 22:13 UTC, mjheilmann commented
Thanks for the work @christopherlai !

2024-06-10 22:14 UTC, merged

2024-06-11 00:33 UTC, christopherlai commented
> Thanks for the work @christopherlai !

Happy to help, but it was purely self-serving. Needed this fix for myself.

What's the schedule for cutting a new release hex?

2024-06-11 02:07 UTC, mjheilmann commented
I'll see about a patch release with this and another bugfix (already merged) probably tomorrow

2024-06-11 14:14 UTC, mjheilmann commented
patch is out as 0.1.4